version: 2

before:
  hooks:
    - go mod tidy

builds:
  - binary: iron
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/IronFE/iron.cli/commands.version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_arm64
    hooks:
      post:
        - sh -c 'if [ "{{ .Os }}" = "$(go env GOHOSTOS)" ] && [ "{{ .Arch }}" = "$(go env GOHOSTARCH)" ]; then mkdir -p ./bin && cp "{{ .Path }}" ./bin/{{ .Name }}; fi'

archives:
  - formats: [binary]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - none*

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
